//Action Types
export const UPDATE_SERCH_OBJ = "UPDATE_SERCH_OBJ";
export const UPDATE_AVAILABILITY_LIST = "UPDATE_AVAILABILITY_LIST";
export const UPDATE_IS_LOADING = "UPDATE_IS_LOADING";
export const UPDATE_AVAILABILITY_META = "UPDATE_AVAILABILITY_META";
export const UPDATE_SELECTED_HOTEL = "UPDATE_SELECTED_HOTEL";
export const UPDATE_SELECTED_HOTEL_STATIC = "UPDATE_SELECTED_HOTEL_STATIC";
export const UPDATE_SELECTED_BOARDS = "UPDATE_SELECTED_BOARDS";
export const UPDATE_SELECTED_ROOMS = "UPDATE_SELECTED_ROOMS";
export const UPDATE_PAX_KEYS = "UPDATE_PAX_KEYS";
export const UPDATE_PAX = "UPDATE_PAX";

//Admin Reports
export const UPDATE_TURNOVER_RESULTS = "UPDATE_TURNOVER_RESULTS";
export const UPDATE_RESERVATION_RESULTS = "UPDATE_RESERVATION_RESULTS";
export const UPDATE_MARKUP_RESULTS = "UPDATE_MARKUP_RESULTS";